name: Build Updater

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: Use Node.js 24
        uses: actions/setup-node@v4
        with:
          node-version: 24.x
          cache: 'pnpm'
      - name: Build Resource file
        run: |
          pnpm install --frozen-lockfile
          pnpm run build:dir
          pnpm run pack:resources
      - name: Deploy
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          commit_message: Update Hot Resource File
          build_dir: ./apps/desktop/build/update
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
