name: Build TEST

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: Use Node.js 24
        uses: actions/setup-node@v4
        with:
          node-version: 24.x
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - run: pnpm run build
