name: Build Updater

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Build Resoure file
        run: |
          yarn --frozen-lockfile
          yarn build:dir
          yarn pack:resources
      - name: Deploy
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          commit_message: Update Hot Resoure File
          build_dir: ./build/update
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
